language: python
python:
- 3.8
- 3.7
install:
- pip install --upgrade pip
- pip install -U tox-travis
- pip install -r requirements_dev.txt
script:
- flake8 oqspy
- flake8 tests
- python setup.py test
- coverage run --source oqspy setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: SvpfR+9+HyeXRyrHhZmvrtjbc0lLo6tqkD6B1fzIP8b3uZKV5AJUnm1q8d8FtJ5S4OS8dxX96wFkCzmKytux1A62VvhrEudJ+kvKga3CSyBJNkawKWR82s6kLfaWXcmh91eZactW2wlv91GkU/vziSIUBGkx1OXHVKhimcidoucD248Q2dkLZX6vd1euspzauijlBsoc+QKFkW3XNiDc2KL7wc3+tZVKZo4lwPt5qYeIJ8lERSldt68rNe8jUeQOW8UvO5yCOLdE25EMIVbPdNt0BOBfvXxR4QRqYOjgHZsuJT+CArklDDc6PxUrVDN8DDrjwcNU3eXWWjO0BywkugFpIrJ+MAnMHCNbYTzyHtAK/7+5B+b0YcQmKRqLSgzYxpMRA6pBOGj6bSHwwueJjLbmzFQKWnawFc0VaDN63YmfF6aZaGhTCetPOoGa2cngOROetPjsr/T+2Ver7KHrmWusDvMx/UgUhCgkIrXWsPw4djGmp2a50k652+yD0pLbsm8KhZlLzvm1rsJ4MgThrCwTustqstbn80ZfDab84UnH4okdMevTFK3liK+EqcLxmSUPgGKBqsXnWTbNC0DWeMfuy3pT0w356PtQi3Y8QM9P122JcfCuG0sLekReH4sVtMWoruB/E/akpDLW1n00Ucg9J7Iv7G4Zj16ppy9zCP0=
  on:
    tags: true
    repo: GillianGrayson/oqspy
    python: 3.8
