language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: GillianGrayson
  password:
    secure: mg7/6dkjHlA6toLzaT8F4jcNff9DEZjecRQiSwUj7thQJCWqQrrl13EkOn6lrURhu1ywQ9tXOuaIAtQcUQBbxoEFqbmN8SsnRLR0/q9Tg8fHiVfPXvjgbpXXAcs5/dRmW6oHKKqLlF+L/ttJE/h5gWLTQtTVpXWeanEP2RgQZ9uVGk7yqdX/6kZV38F1ufK5XKvfetzlv/kYm/Jd4hiTAd5zNAJoPhjcj7+6JsOGhu7uQrhfinUMKRU4xlpaBFaCa4/qrg7ZaQv/ZMNctsRXUc+u9yzKm+4l1/ey9ADT4FqMwy9ydaaOMF/RrbSp5EfUjSDFAxtxvEWNg3AN+htgc1fXfNqOGmfMeATtYbFTnj8IWmQifqSrcP55h+vZvlLTWuoSkiQeJfCNczRgdJlksp47qdcpYMBlVYBybKTqSlh1q79NdEE17sXtoXuZ3nyC/SL+vHeIfqsaes5Kh8eM0DTO40NODkGYTM+WRU/La/zrsKqa5znVqe3Zf0jZ+o8pe9J6iA1KKFcJH+Inf/w8sajm4+FfDfjPqv3hEYDZOFHz6Z8aETT1B1tRMZMvGwnDvPAdSmhGb37bjIBJnvcAmicDo3YMN/zQqEIqZFzePPGXA07J5kPyRb4gZEAOj+DJF+cAtp8ziSwplDhJki7aeYlo/+cYGWxFBGKdiyvejlE=
  on:
    tags: true
    repo: GillianGrayson/oqspy
    python: 3.8
