language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: GillianGrayson
  password:
    secure: T4y0itUnK89MHdd8iw9kdFdhRP0yExIEJA5wh/PQkUMp//7CXbi9jjmnaBfgo1Au8XW2/GUIYHtNjZHZX2vgnL0fcuy2BI4txNgilhAdhrHBXfE+eY5H4kJk4t7MbdzKcO4QEKkFwWPjXeC2aSogZ2gzBgD/ERl58b18lCSqBiplgmnFu8Wu0Mq0AbptYT0IJWs/jjJCPyyBBcz0xSSbyDPYjWxwqRaLrJ9osEbp2hEnoGQBPtLCg5VYLNbofdW+zZ8nqJ8CHJrlFKjWNsm4FwIu/82wbwMUnGyWNySOWY/Xyvht2I0NvhSnUaOgHWoCb3B1Gy26KdxY7ykSdMqWqXeTGEuL8mOhnQzHrOCWQTByNp6YfhckzpVm4cO6g6d5Q3P0Jdr+GTXzS39aYkmVnMT6hC1zdUyrVLiyD9y6HiUbqKz7qq5HUpk/3/+DDZN7Hm6GSqVdgPuK+R2Vt2MMpG9G4P3X12oC8dypPJOzTWWm2eNtAM1gUFtjRW/CoVn9jT6+Ups5bSdOr8+FwrQSStJWCrSZkVfyfxz41ncolkKlszveBBvPcDacKEGyyH+yPfHg5Ks0kCYQ/ro/S0EI9VRa5dw95m+6ZG6BUeQBCm9HVdCtg3hnaBw45AQdSy6Lz8duz1doKWWyQ1gwtWNEsD/nMXxV84/tZfZY2ekIWBk=
  on:
    tags: true
    repo: GillianGrayson/oqspy
    python: 3.8
